server:
  port: 8082

spring:
  profiles:
    # ??????? dev ???? / test ????  / prod ????
    active: dev-secrets
  config:
    import:
      - optional:nacos:application.yml  # 从 Nacos 导入配置
  # WARN 47916 --- [  restartedMain] c.a.c.n.registry.NacosServiceRegistry    : No service to register for nacos client...
  # 如果你希望把当前应用注册到 Nacos（推荐）
  application:
    # discovery - enabled - true - nacos - 服务管理 - 服务列表
    # 当前服务的名称
    name: gateway    # 必须配置应用名
  cloud:
    nacos:
      discovery:
        enabled: true    # 打开服务发现/注册功能
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:public}
      config:
        # nacos 配置中心的网络域
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
        # nacos 配置中心的命名空间 http://127.0.0.1:8848/nacos/ 新建命名空间
        namespace: ${NACOS_NAMESPACE:public}
        # nacos 配置中心的分组
        group: DEFAULT_GROUP
        # nacos 配置中心的配置文件类型（yaml 或 properties）
        file-extension: yaml
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        # 共享配置
        shared-configs:
          - data-id: gateway-routes.yaml
            group: DEFAULT_GROUP
            refresh: true
    gateway:
      discovery:
        locator:
          # 比如你有订单服务 order-service 也注册到了 Nacos，网关自动可以转发到：
          #http://localhost:8081/order-service/api/orders/...
          enabled: true # 开启从 nacos 注册中心动态创建路由
          lower-case-service-id: true # 服务名小写